export const GET_ARTICLE_DETAIL = 'GET_ARTICLE_DETAIL'
export const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST'
export const SHOW_MESSAGE = 'SHOW_MESSAGE'
export const UPDATE_START_INDEX = 'UPDATE_START_INDEX'
